In [1]:
import pandas as pd
import numpy as np

Loading and inspectin Data:

In [2]:
df = pd.read_csv("data.csv")

df.head()  # first 5 rows

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [5]:
df.shape   # (rows, columns)

(32, 5)

In [4]:

df.info() # column names, non-null counts, dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [6]:
df.describe() # summary statistics for numeric columns

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

Selecting and filtering:

In [7]:
df["Pulse"]  # a single column (Series)

0     110
1     117
2     103
3     109
4     117
5     102
6     110
7     104
8     109
9      98
10    103
11    100
12    100
13    106
14    104
15     98
16     98
17    100
18     90
19    103
20     97
21    108
22    100
23    130
24    105
25    102
26    100
27     92
28    103
29    100
30    102
31     92
Name: Pulse, dtype: int64

In [13]:
df[["Pulse", "Calories"]]  # multiple columns (DataFrame)

    Pulse  Calories
0     110     409.1
1     117     479.0
2     103     340.0
3     109     282.4
4     117     406.0
5     102     300.0
6     110     374.0
7     104     253.3
8     109     195.1
9      98     269.0
10    103     329.3
11    100     250.7
12    100     250.7
13    106     345.3
14    104     379.3
15     98     275.0
16     98     215.2
17    100     300.0
18     90       NaN
19    103     323.0
20     97     243.0
21    108     364.2
22    100     282.0
23    130     300.0
24    105     246.0
25    102     334.5
26    100     250.0
27     92     241.0
28    103       NaN
29    100     280.0
30    102     380.3
31     92     243.0

In [15]:
df[df["Duration"] < 60] #filter rows based on a condition (Duration < 60)

    Duration          Date  Pulse  Maxpulse  Calories
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
8         30  '2020/12/09'    109       133     195.1
18        45  '2020/12/18'     90       112       NaN
20        45  '2020/12/20'     97       125     243.0
22        45           NaN    100       119     282.0
24        45  '2020/12/24'    105       132     246.0

In [16]:
df.loc[df["Duration"] < 60 , "Maxpulse"] # for rows where Duration < 60 , show only the Maxpulse column

3     175
4     148
8     133
18    112
20    125
22    119
24    132
Name: Maxpulse, dtype: int64

Cleaning Data:

In [19]:
df.isnull().sum()  # check for missing values (NaN) in the DataFrame per column

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [20]:
df["Calories"].fillna(df["Calories"].mean(), inplace=True) # fill missing values in Calories column with the mean of that column

C:\Users\Masters Computer\AppData\Local\Temp\ipykernel_4220\1110785228.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Calories"].fillna(df["Calories"].mean(), inplace=True) # fill missing values in Calories column with the mean of that column

In [ ]:
df.dropna(inplace=True) # drop rows with any missing values

In [21]:
df.drop_duplicates(inplace=True) # drop duplicate rows

Grouping & Aggregation:

In [24]:
df.groupby("Duration")["Pulse"].mean() # group by Duration and calculate the mean of Pulse

Duration
30     109.000000
45     103.000000
60     103.521739
450    104.000000
Name: Pulse, dtype: float64

In [23]:
df.groupby("Duration")[["Pulse", "Maxpulse", "Calories"]].mean()

               Pulse    Maxpulse    Calories
Duration
30        109.000000  133.000000  195.100000
45        103.000000  135.166667  294.013333
60        103.521739  126.695652  316.807826
450       104.000000  134.000000  253.300000

In [26]:
df.groupby("Duration").agg({"Pulse": "mean", "Maxpulse": "max", "Calories": "mean"}) # group by Duration and aggregate multiple columns with different functions

               Pulse  Maxpulse    Calories
Duration
30        109.000000       133  195.100000
45        103.000000       175  294.013333
60        103.521739       147  316.807826
450       104.000000       134  253.300000